-- User master table
-- The table definition allows BIGINT or UUID for user_id.
-- This DDL uses a portable BIGINT identity primary key.

CREATE TABLE m_user (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(100) NOT NULL,
    display_name VARCHAR(200),
    email VARCHAR(255) NOT NULL,
    phone_number VARCHAR(50),
    CONSTRAINT pk_m_user PRIMARY KEY (user_id),
    CONSTRAINT uq_m_user_username UNIQUE (username),
    CONSTRAINT uq_m_user_email UNIQUE (email)
);
